#!/bin/sh

# This repo is only valid for EL (i.e. CentOS and RHEL)

case "$WARI_DISTRO" in
fedora)
  ;;
rhel)
  add_yum_repo_rpm http://download.fedoraproject.org/pub/epel/epel-release-latest-$(rpm -E %rhel).noarch.rpm
  ;;
centos)
  add_yum_repo_rpm http://download.fedoraproject.org/pub/epel/epel-release-latest-$(rpm -E %rhel).noarch.rpm
  ;;
opensuse)
  ;;
ubuntu)
  ;;
arch)
  ;;
*)
  ;;
esac
