#!/bin/sh

case "$WARI_DISTRO" in
fedora)
  add_copr_repo mantid/mantid
  ;;
rhel)
  add_yum_repo_url https://copr.fedoraproject.org/coprs/mantid/mantid/repo/epel-$(rpm -E %rhel)/mantid-mantid-epel-$(rpm -E %rhel).repo
  ;;
centos)
  add_yum_repo_url https://copr.fedoraproject.org/coprs/mantid/mantid/repo/epel-$(rpm -E %rhel)/mantid-mantid-epel-$(rpm -E %rhel).repo
  ;;
opensuse)
  ;;
ubuntu)
  sudo add-apt-repository ppa:mantid/mantid
  ;;
arch)
  ;;
*)
  ;;
esac
