#!/bin/sh

case "$WARI_DISTRO" in
fedora)
  add_yum_repo_url https://negativo17.org/repos/fedora-nvidia.repo
  ;;
rhel)
  add_yum_repo_url https://negativo17.org/repos/epel-nvidia.repo
  ;;
centos)
  add_yum_repo_url https://negativo17.org/repos/epel-nvidia.repo
  ;;
opensuse)
  ;;
ubuntu)
  sudo add-apt-repository -y ppa:graphics-drivers/ppa
  ;;
arch)
  ;;
*)
  ;;
esac
