#!/bin/sh

case "$WARI_DISTRO" in
fedora)
  add_yum_repo_rpm http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
  ;;
rhel)
  ;;
centos)
  ;;
opensuse)
  ;;
ubuntu)
  ;;
arch)
  ;;
*)
  ;;
esac
